[CC-4623] Improve 3DS handling
xendit/xendit-sdk-ios-src pull request #37
Opened 2021-06-09 04:48 UTC by zakiarsyad

## Description
1. Only perform the retry for 3DS 2.0 transaction.
Not perform retry for 3DS 1.0 transaction -> [splunk](https://splunk.tidnex.com/en-US/app/search/search?q=search%2060c0456e62e5810020bb656b%20%7C%20spath%20message%20%7C%20search%20message%3D%22Outgoing%20response%22%7C%20spath%20service%20%7C%20search%20service%3D%22xendit-cc-gateway%22&display.page.search.mode=fast&dispatch.sample_ratio=1&earliest=1623196800&latest=1623283200&sid=1623213455.569414)
perform retry for 3DS 2.0 transaction -> [splunk](https://splunk.tidnex.com/en-US/app/search/search?q=search%2060c0405d8c4b060020878e01%20%7C%20spath%20message%20%7C%20search%20message%3D%22Outgoing%20response%22%7C%20spath%20service%20%7C%20search%20service%3D%22xendit-cc-gateway%22&display.page.search.mode=fast&dispatch.sample_ratio=1&earliest=1623196800&latest=1623283200&sid=1623212233.564712)

2. Handle failed transaction on tokenization step (Bypassed Authentication test case)
<img width="395" alt="Screen Shot 2021-06-09 at 11 22 15" src="https://user-images.githubusercontent.com/47877695/121294731-1134c080-c918-11eb-89a7-3066c00bb31b.png">

## Test
- Success transaction
<img width="362" alt="Screen Shot 2021-06-09 at 11 38 52" src="https://user-images.githubusercontent.com/47877695/121294807-3295ac80-c918-11eb-9068-9cec9163dc99.png">

- MIGS DIRECT transaction
<img width="366" alt="Screen Shot 2021-06-09 at 11 48 31" src="https://user-images.githubusercontent.com/47877695/121295062-a1730580-c918-11eb-869e-ddaaf7829936.png">

2021-06-09 07:12 UTC, javiersuweijie approved these changes
LGTM 
needa bump the patch here
https://github.com/xendit/xendit-sdk-ios-src/blob/master/Xendit.podspec#L3

2021-06-10 04:56 UTC, zakiarsyad commented
return failure reason for FAILED 3DS
<img width="370" alt="Screen Shot 2021-06-10 at 11 51 36" src="https://user-images.githubusercontent.com/47877695/121467161-cfbd1780-c9e2-11eb-85a5-f42c991809f6.png">

2021-06-10 06:13 UTC, javiersuweijie requested changes

2021-06-10 06:13 UTC, javiersuweijie commented on Xendit.podspec
> +  s.version      = "3.2.1"
3.3.0

2021-06-11 04:07 UTC, merged